# Generated by Django 4.2.1 on 2023-06-18 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_nombre', models.CharField(max_length=50)),
                ('prod_precio', models.IntegerField()),
                ('prod_stock', models.IntegerField()),
                ('prod_descripcion', models.CharField(max_length=150)),
                ('prod_img_url', models.ImageField(upload_to='imagenesProducto')),
                ('prod_fecha_inicio', models.DateField(auto_now_add=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webHuertita.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('appaterno', models.CharField(max_length=50)),
                ('apmaterno', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=80)),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('contraseña', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('depto', models.CharField(max_length=6)),
                ('region', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
                ('comuna', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webHuertita.productos')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webHuertita.usuarios')),
            ],
        ),
    ]
