# Generated by Django 4.2.1 on 2023-06-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Planta',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombreUser',
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default=50, max_length=80),
            preserve_default=False,
        ),
    ]
