# Generated by Django 4.2.2 on 2023-06-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0003_rename_producto_planta_remove_user_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contrasena',
            field=models.CharField(default=8, max_length=10),
            preserve_default=False,
        ),
    ]
