# Generated by Django 4.2.2 on 2023-06-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0004_user_contrasena'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planta',
            new_name='Producto',
        ),
    ]
