# Generated by Django 4.2.2 on 2023-06-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0005_rename_planta_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('appaterno', models.CharField(max_length=50)),
                ('apmaterno', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=80)),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField()),
                ('contraseña', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('depto', models.CharField(max_length=6)),
                ('region', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
                ('comuna', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
