# Generated by Django 4.2.2 on 2023-06-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0006_usuarios_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
