# Generated by Django 4.2.2 on 2023-06-22 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0009_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='webHuertita.genero'),
            preserve_default=False,
        ),
    ]
