# Generated by Django 4.2.1 on 2023-06-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0010_remove_usuario_genero_usuario_genero_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img_perf',
            field=models.ImageField(default=1, upload_to='imagenesPerfiles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='depto',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
