# Generated by Django 4.2.1 on 2023-06-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0011_usuario_img_perf_alter_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='genero_id',
            new_name='genero',
        ),
    ]
