# Generated by Django 4.2.2 on 2023-07-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0013_usuario_username_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='rut_usu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webHuertita.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='categoria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webHuertita.categoria'),
        ),
    ]
