# Generated by Django 4.2.2 on 2023-07-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0019_alter_usuario_celular_alter_usuario_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apmaterno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='appaterno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
