# Generated by Django 4.2.2 on 2023-07-07 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0020_alter_usuario_apmaterno_alter_usuario_appaterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='webHuertita.genero'),
        ),
    ]
