# Generated by Django 4.2.2 on 2023-07-07 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0022_alter_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='categoria',
            new_name='categoria_id',
        ),
    ]
