# Generated by Django 4.2.2 on 2023-07-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0023_rename_categoria_producto_categoria_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
