# Generated by Django 4.2.2 on 2023-07-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0025_rename_categoria_venta_categoria_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='categoria_id',
        ),
    ]
