# Generated by Django 4.2.2 on 2023-07-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webHuertita', '0026_remove_venta_categoria_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
